; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:native]
platform = native
build_src_filter = +<logic.cpp>
build_flags = -I"${PROJECT_DIR}/src"
test_build_src = yes
lib_deps = throwtheswitch/Unity@^2.6.1

[mock_base]
lib_deps = 
	joaolopesf/SerialDebug@^0.9.82
	bblanchon/ArduinoTrace@^1.2.0
	throwtheswitch/Unity@^2.6.1

[env:dfrobot_firebeetle2_esp32e]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	joaolopesf/SerialDebug@^0.9.82
	throwtheswitch/Unity@^2.6.1

[env:mock_cap_dry_res_dry_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_LOW

[env:mock_cap_dry_res_dry_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_NORMAL

[env:mock_cap_dry_res_dry_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_HIGH

[env:mock_cap_dry_res_wet_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_WET -D MOCK_TEMP_LOW

[env:mock_cap_dry_res_wet_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_WET -D MOCK_TEMP_NORMAL

[env:mock_cap_dry_res_wet_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_WET -D MOCK_TEMP_HIGH

[env:mock_cap_dry_res_moist_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_LOW

[env:mock_cap_dry_res_moist_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_NORMAL

[env:mock_cap_dry_res_moist_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_DRY -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_HIGH

[env:mock_cap_wet_res_dry_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_LOW

[env:mock_cap_wet_res_dry_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_NORMAL

[env:mock_cap_wet_res_dry_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_HIGH

[env:mock_cap_wet_res_wet_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_WET -D MOCK_TEMP_LOW

[env:mock_cap_wet_res_wet_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_WET -D MOCK_TEMP_NORMAL

[env:mock_cap_wet_res_wet_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_WET -D MOCK_TEMP_HIGH

[env:mock_cap_wet_res_moist_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_LOW

[env:mock_cap_wet_res_moist_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_NORMAL

[env:mock_cap_wet_res_moist_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_WET -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_HIGH

[env:mock_cap_moist_res_dry_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_LOW

[env:mock_cap_moist_res_dry_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_NORMAL

[env:mock_cap_moist_res_dry_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_DRY -D MOCK_TEMP_HIGH

[env:mock_cap_moist_res_wet_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_WET -D MOCK_TEMP_LOW

[env:mock_cap_moist_res_wet_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_WET -D MOCK_TEMP_NORMAL

[env:mock_cap_moist_res_wet_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_WET -D MOCK_TEMP_HIGH

[env:mock_cap_moist_res_moist_low]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_LOW

[env:mock_cap_moist_res_moist_normal]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_NORMAL

[env:mock_cap_moist_res_moist_high]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino
lib_deps = 
	${mock_base.lib_deps}
build_flags = -D MOCK_SENSORS -D MOCK_CAPACITIVE_MOIST -D MOCK_RESISTIVE_MOIST -D MOCK_TEMP_HIGH
