#pragma region PIN DEFINITIONS

#define TEMP_SENSOR A0       // 36
#define CAPACITIVE_SENSOR A1 // 39
#define RESISTIVE_SENSOR A2  // 34
#define PUMP_RELAY_PIN D2    // 25
#pragma endregion

#pragma region CONSTANTS

#define CAPACITIVE_DRY_MAX 3000
#define CAPACITIVE_DRY_MIN 2800

#define CAPACITIVE_MOIST_MAX 2799
#define CAPACITIVE_MOIST_MIN 2400

#define CAPACITIVE_WET_MAX 2399
#define CAPACITIVE_WET_MIN 1400

#define RESISTIVE_DRY_MIN 0
#define RESISTIVE_DRY_MAX 250

#define RESISTIVE_MOIST_MIN 251
#define RESISTIVE_MOIST_MAX 1500

#define RESISTIVE_WET_MIN 1501
#define RESISTIVE_WET_MAX 3000

#define TEMP_PUMP_THRESHOLD_C 25
#define PUMP_ON_DURATION_MS 5000
#define PUMP_CHECK_INTERVAL_MS 1000

#pragma endregion
